declare const styles: {
  readonly "pg-build__align-center": string;
  readonly "pg-build__align-left": string;
  readonly "pg-build__align-right": string;
  readonly "pg-build__breadcrumb": string;
  readonly "pg-build__breadcrumb-item": string;
  readonly "pg-build__button": string;
  readonly "pg-build__card": string;
  readonly "pg-build__card-body": string;
  readonly "pg-build__card-foot": string;
  readonly "pg-build__card-head": string;
  readonly "pg-build__col": string;
  readonly "pg-build__col-1": string;
  readonly "pg-build__col-10": string;
  readonly "pg-build__col-11": string;
  readonly "pg-build__col-12": string;
  readonly "pg-build__col-2": string;
  readonly "pg-build__col-3": string;
  readonly "pg-build__col-4": string;
  readonly "pg-build__col-5": string;
  readonly "pg-build__col-6": string;
  readonly "pg-build__col-7": string;
  readonly "pg-build__col-8": string;
  readonly "pg-build__col-9": string;
  readonly "pg-build__img": string;
  readonly "pg-build__img-full-width": string;
  readonly "pg-build__img-rounded": string;
  readonly "pg-build__link": string;
  readonly "pg-build__modal-style": string;
  readonly "pg-build__row": string;
  readonly "pg-build__tab": string;
  readonly "pg-build__tab-content": string;
  readonly "pg-build__tab-item": string;
};
export = styles;

